#!/bin/bash
#SBATCH -A TG-CCR140008 # 2017 XSEDE Applications of Parallel Computing Course Allocation
#SBATCH -J particle-openmp16
#SBATCH -o particle-openmp16.stdout
#SBATCH -n 16         
#SBATCH -p normal
#SBATCH -t 00:10:00     
#SBATCH -N 1        

export OMP_NUM_THREADS=16
./openmp -n 1000 -o openmp.txt
