#!/bin/bash
#SBATCH -A TG-CCR140008 # 2017 XSEDE Applications of Parallel Computing Course Allocation
#SBATCH -J particle-mpi16
#SBATCH -o particle-mpi16.stdout
#SBATCH -N 16 
#SBATCH -n 16         
#SBATCH -p normal
#SBATCH -t 00:10:00     
ibrun ./mpi -n 1000 -o mpi.txt
