#!/bin/bash
#SBATCH -A TG-CCR140008 # 2017 XSEDE Applications of Parallel Computing Course Allocation
#SBATCH -J particle-serial
#SBATCH -o particle-serial.stdout
#SBATCH -n 1         
#SBATCH -p normal
#SBATCH -t 00:10:00     
#SBATCH -N 1         
./serial -n 1000 -o serial.txt
