#!/bin/bash
#SBATCH -A TG-CCR140008 # 2017 XSEDE Applications of Parallel Computing Course Allocation
#SBATCH -J particle-pthreads16
#SBATCH -o particle-pthreads16.stdout
#SBATCH -n 16         
#SBATCH -p normal
#SBATCH -t 00:10:00     
#SBATCH -N 1         
./pthreads -p 16 -n 1000 -o pthreads.txt
