#!/bin/bash -l
#SBATCH -p main # change this option for non-debug runs
#SBATCH -t 00:25:00
#SBATCH -N 1
#SBATCH -o mpi16.%j.stdout
#SBATCH -e mpi16.%j.error

rm mpi.txt
mpirun -n 1 ./serial -n 500 -no -s mpi.txt
mpirun -n 1 ./mpi -n 500 -no -s mpi.txt
mpirun -n 2 ./mpi -n 500 -no -s mpi.txt
mpirun -n 4 ./mpi -n 500 -no -s mpi.txt
mpirun -n 8 ./mpi -n 500 -no -s mpi.txt
mpirun -n 16 ./mpi -n 500 -no -s mpi.txt
mpirun -n 2 ./mpi -n 1000 -no -s mpi.txt
mpirun -n 4 ./mpi -n 2000 -no -s mpi.txt
mpirun -n 8 ./mpi -n 4000 -no -s mpi.txt
mpirun -n 16 ./mpi -n 8000 -no -s mpi.txt
./autograder -v mpi -s mpi.txt
