#!/bin/bash 
#SBATCH -p main
#SBATCH -t 00:30:00
#SBATCH -o serial.%j.stdout
#SBATCH -e serial.%j.error
#SBATCH -N 1

rm serial.txt
./serial -n 500 -no -s serial.txt
./serial -n 1000 -no -s serial.txt
./serial -n 2000 -no -s serial.txt
./serial -n 4000 -no -s serial.txt
./serial -n 8000 -no -s serial.txt
./autograder -v serial -s serial.txt
