#!/bin/bash -l
#SBATCH -p main # change this option for non-debug runs
#SBATCH -t 00:20:00
#SBATCH -o openmp16.%j.stdout
#SBATCH -e openmp16.%j.error
#SBATCH -N 1

rm openmp.txt
./serial -n 500 -no -s openmp.txt
export OMP_NUM_THREADS=1
./openmp -n 500 -no -s openmp.txt
export OMP_NUM_THREADS=2
./openmp -n 500 -no -s openmp.txt
export OMP_NUM_THREADS=4
./openmp -n 500 -no -s openmp.txt
export OMP_NUM_THREADS=8
./openmp -n 500 -no -s openmp.txt
export OMP_NUM_THREADS=16
./openmp -n 500 -no -s openmp.txt
export OMP_NUM_THREADS=2
./openmp -n 1000 -no -s openmp.txt
export OMP_NUM_THREADS=4
./openmp -n 2000 -no -s openmp.txt
export OMP_NUM_THREADS=8
./openmp -n 4000 -no -s openmp.txt
export OMP_NUM_THREADS=16
./openmp -n 8000 -no -s openmp.txt
./autograder -v openmp -s openmp.txt
